[project]
name = "advent_of_code_2025"
version = "0.1.0"
description = "Advent of Code 2025 Project"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[tool.uv.workspace]
members = ["day1"]
